### ISSUE TITLE
Hello! There is crash in 'bundle install'

### ISSUE THREAD

**Issue by Joeycho** [learn-co-students/rails-long-running-tasks-readme-v-000#845]
Currently, there is issue in 'bundle install'.

Stuck when installing json(1.8.3), and bundler said that i cannot continue anymore.

When installing gem by 'gem install json -v '1.8.3', the below error message came out.

When I tried with down-graded version(1.7.3) bundler' bundle _1.7.3_ install', 

I stuck in the same situation.

Is there any clear or better guide how to handle gem, version control?

It is quite frustrating since it blocks the starting point to code.

Any helps or advice will be highly appreciated! :)
-------------------------------------------------------------------
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
Joeys-MacBook-Air:rails-long-running-tasks-readme-v-000 Joey$ gem  install json -v '1.8.3'
Building native extensions. This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /Users/Joey/.rvm/gems/ruby-2.6.1/gems/json-1.8.3/ext/json/ext/generator
/Users/Joey/.rvm/rubies/ruby-2.6.1/bin/ruby -I /Users/Joey/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0 -r ./siteconf20190426-84085-1bk9aa1.rb extconf.rb
creating Makefile

current directory: /Users/Joey/.rvm/gems/ruby-2.6.1/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/Joey/.rvm/gems/ruby-2.6.1/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c:861:25: error: use of undeclared identifier 'rb_cFixnum'
    } else if (klass == rb_cFixnum) {
                        ^
generator.c:863:25: error: use of undeclared identifier 'rb_cBignum'
    } else if (klass == rb_cBignum) {
                        ^
2 errors generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/Joey/.rvm/gems/ruby-2.6.1/gems/json-1.8.3 for inspection.
Results logged to /Users/Joey/.rvm/gems/ruby-2.6.1/extensions/x86_64-darwin-17/2.6.0/json-1.8.3/gem_make.out

**Comment by chrissygonzalez** [comment]
I'm having the same problem

**Comment by Marie-Burns22** [comment]
I also had the same problem.  I tried the suggestions  provided in the error messages, but was not able to get the server to run.

**Comment by anihakutin** [comment]
**Hey Everyone!**
Had the same issue.

_**Here's how I got it to run:**_

**Downgrade Ruby and Rails**
- Switch your ruby version to 2.3.3, if using rvm `rvm use 2.3.3` or `rvm install "ruby-2.3.3"` if you don't have 2.3.3 installed
- Install rails again for current ruby version(2.3.3) `gem install rails -v 4.2.5 --no-doc`

**Make the following changes to your gem file:**
- Specify version number to spring gem `gem 'spring', '2.0.0'`
- Specify version number for sqlite3 gem `gem 'sqlite3', '~> 1.3.6'`

**Start 'er up:**
- `Bundle install`
- `rake db:migrate`
- `rails s`

**Should be good to go!**
HT @jonfoster9999

**Comment by Joeycho** [comment]
@anihakutin 
Oh, thanks for sharing your solution!

Probably, it's time to close the lab for me as well. When I checked it, it's still open.

Hope yours also works for me :)

**Comment by Joeycho** [comment]
Well, when I just checked right now, there was no error occurs.

With 
`rails db:migrate`
`rails s`

Those were enough. But obviously I had an issue like the above!

**Comment by Joeycho** [comment]
So close the issue now :)
